export interface SvgProps extends React.SVGProps<SVGSVGElement> {
  fill?: string;
}

export { default as IconPlay } from "./play";
export { default as IconNext } from "./next";
export { default as IconPrev } from "./prev";
export { default as IconPause } from "./pause";
export { default as IconSpeakerLarge } from "./speaker-large";
export { default as IconSpeakerLow } from "./speaker-low";
export { default as IconSpeakerMute } from "./speaker-mute";
export { default as IconLibrary } from "./library";
export { default as IconCollect } from "./collect";
export { default as IconTopArrow } from "./top-arrow";
export { default as IconRightArrow } from "./right-arrow";
export { default as IconBottomArrow } from "./bottom-arrow";
export { default as IconLeftArrow } from "./left-arrow";
export { default as IconRepeat } from "./repeat";
export { default as IconShuffle } from "./shuffle";
export { default as IconMoreHorizontal } from "./more-horizontal";
export { default as IconMoreVertical } from "./more-vertical";
export { default as IconSearch } from "./search";
export { default as IconNavigation } from "./navigation";
export { default as IconLoading } from "./loading";
export { default as IconHeart } from "./heart";
export { default as IconSetting } from "./setting";
export { default as IconSun } from "./sun";
export { default as IconMoon } from "./moon";
export { default as IconMusicList } from "./music-list";
export { default as IconRhythm } from "./rhythm";
export { default as IconStyle } from "./style";
export { default as IconDrink } from "./drink";
export { default as IconGrid } from "./grid";
export { default as IconGlobal } from "./global";
export { default as IconSmile } from "./smile";
export { default as IconPlayThread } from "./play-thread";
export { default as IconHeartThread } from "./heart-thread";
export { default as IconEmail } from "./email";
export { default as IconLock } from "./lock";
export { default as IconGithub } from "./github";
export { default as IconNCloudLogo } from "./ncloud-logo";
export { default as IconPhone } from "./phone";
